AT-1 Initial commit
YehorKorotun/Task1 pull request #1
Opened 2020-10-20 18:17 UTC by YehorKorotun

2020-10-20 20:59 UTC, AliceIgorevna requested changes
Tasks itself performed very well. This comment is mostly about improvements. Based on the level that you implemented this tasks, I propose you to go ahead with further harder improvements. So these comments are, shall we say, for the 'more advanced user' of this language

2020-10-20 20:59 UTC, AliceIgorevna commented on .idea/.gitignore
> +misc.xml
you can use alias *.xml to ignore all XML files

2020-10-20 20:59 UTC, AliceIgorevna commented on .idea/.gitignore
> +Task1.iml
same for IML files

2020-10-20 20:59 UTC, AliceIgorevna commented on src/com/yehorkorotun/taskfirst/Main.java
> +        fillArray.randomArray();
is you're using this object only once, you can inline this assignment: new FillArray(). randomArray();

2020-10-20 20:59 UTC, AliceIgorevna commented on src/com/yehorkorotun/taskfirst/task1/FillArray.java
> +            System.out.println(randomArray[i] + " ");
you can print array out of the loop, once it is filled already

2020-10-20 20:59 UTC, AliceIgorevna commented on src/com/yehorkorotun/taskfirst/task1/FillArray.java
> +            randomArray[i] = (int) ((Math.random() * 30) - 15);
why do you use a bound from 15 to 30? It would be pseudorandom element.

2020-10-20 20:59 UTC, AliceIgorevna commented on src/com/yehorkorotun/taskfirst/task2/NumberOfLines.java
> +    private Scanner scanner = new Scanner(System.in);
why won't you use a constructor to assign values to elements?

2020-10-20 20:59 UTC, AliceIgorevna commented on src/com/yehorkorotun/taskfirst/task3/MathOperations.java
> +    private Scanner scanner = new Scanner(System.in);
same as above

2020-10-20 20:59 UTC, AliceIgorevna commented on src/com/yehorkorotun/taskfirst/task3/MathOperations.java
> +        firstNumber = scanner.nextInt();
in case if I would fill it with NOT expected data, exception would be thrown, try to handle this case

2020-10-20 20:59 UTC, AliceIgorevna commented on src/com/yehorkorotun/taskfirst/task3/MathOperations.java
> +        secondNumber = scanner.nextInt();
same as above

2020-10-20 20:59 UTC, AliceIgorevna commented on src/com/yehorkorotun/taskfirst/Main.java
> +        System.out.println("Task2: ");
Task 3

2020-10-20 20:59 UTC, AliceIgorevna commented on src/com/yehorkorotun/taskfirst/task3/MathOperations.java
> +        firstNumber = scanner.nextInt();
same for previous task

2020-10-21 08:08 UTC, YehorKorotun commented on .idea/.gitignore
> +misc.xml
Done

2020-10-21 08:09 UTC, YehorKorotun commented on .idea/.gitignore
> +Task1.iml
Done

2020-10-21 08:11 UTC, YehorKorotun commented on src/com/yehorkorotun/taskfirst/Main.java
> +        fillArray.randomArray();
Modified

2020-10-21 10:01 UTC, YehorKorotun commented on src/com/yehorkorotun/taskfirst/task1/FillArray.java
> +            System.out.println(randomArray[i] + " ");
Modified

2020-10-21 10:02 UTC, YehorKorotun commented on src/com/yehorkorotun/taskfirst/task1/FillArray.java
> +            randomArray[i] = (int) ((Math.random() * 30) - 15);
Modified

2020-10-21 10:07 UTC, YehorKorotun commented on src/com/yehorkorotun/taskfirst/Main.java
> +        System.out.println("Task2: ");
Modified

2020-10-21 11:11 UTC, YehorKorotun commented on src/com/yehorkorotun/taskfirst/task2/NumberOfLines.java
> +    private Scanner scanner = new Scanner(System.in);
Modified

2020-10-21 11:11 UTC, YehorKorotun commented on src/com/yehorkorotun/taskfirst/task3/MathOperations.java
> +    private Scanner scanner = new Scanner(System.in);
Modified

2020-10-21 17:22 UTC, YehorKorotun commented on src/com/yehorkorotun/taskfirst/task3/MathOperations.java
> +        firstNumber = scanner.nextInt();
Modified

2020-10-21 17:31 UTC, YehorKorotun commented on src/com/yehorkorotun/taskfirst/task3/MathOperations.java
> +        secondNumber = scanner.nextInt();
Modified

2020-10-21 19:43 UTC, AliceIgorevna requested changes
Need to think over implementation of two tasks. One is good, no changes needed

2020-10-21 19:43 UTC, AliceIgorevna commented on src/com/yehorkorotun/taskfirst/task2/NumberOfLines.java
> +    }
Seems that you don't get my idea.
I meant constructor without any parameters. YOu still assign to scanner value outside of the constructor in line 12.
I meant smth like:
public void NumberOfLines (){
         this.scanner = new Scanner(System.in);
    }

without any additional changes

2020-10-21 19:43 UTC, AliceIgorevna commented on src/com/yehorkorotun/taskfirst/task2/NumberOfLines.java
> +        }
this is good 👍

2020-10-21 19:43 UTC, AliceIgorevna commented on src/com/yehorkorotun/taskfirst/task2/NumberOfLines.java
> +    }
If I would call this method before enterNumbersAndValuesOfLines() what would be a result? Like I mean that currently you have 2 dependent methods, that is not good idea.

2020-10-21 19:43 UTC, AliceIgorevna commented on src/com/yehorkorotun/taskfirst/task3/MathOperations.java
> +    }
same as above

2020-10-21 19:43 UTC, AliceIgorevna commented on src/com/yehorkorotun/taskfirst/task3/MathOperations.java
> +        System.out.print("Your result is: " + resultOfCalculation);
same, if I would  call this method before enterNumbers(), what would I get?

2020-10-21 19:43 UTC, AliceIgorevna commented on src/com/yehorkorotun/taskfirst/task1/FillArray.java
> +    }
this one is good 👍

2020-10-21 19:49 UTC, YehorKorotun commented on src/com/yehorkorotun/taskfirst/task2/NumberOfLines.java
> +        }
thanks a lot))

2020-10-21 19:52 UTC, YehorKorotun commented on src/com/yehorkorotun/taskfirst/task2/NumberOfLines.java
> +    }
Now I got it))
Modified.

2020-10-21 19:52 UTC, YehorKorotun commented on src/com/yehorkorotun/taskfirst/task2/NumberOfLines.java
> +    }
Got it, modified.

2020-10-21 19:53 UTC, YehorKorotun commented on src/com/yehorkorotun/taskfirst/task3/MathOperations.java
> +    }
Modified

2020-10-21 19:55 UTC, YehorKorotun commented on src/com/yehorkorotun/taskfirst/task3/MathOperations.java
> +        System.out.print("Your result is: " + resultOfCalculation);
Modified

2020-10-21 19:56 UTC, YehorKorotun commented on src/com/yehorkorotun/taskfirst/task1/FillArray.java
> +    }
thanks)

2020-10-25 21:27 UTC, AliceIgorevna approved these changes
Generally approved, but can be improved

2020-10-25 21:27 UTC, AliceIgorevna commented on src/com/yehorkorotun/taskfirst/task3/MathOperations.java
> +    public void enterNumbersAndCalculation () {
in this case - 'enterNumbersAndCalculate()'

2020-10-25 21:27 UTC, AliceIgorevna commented on src/com/yehorkorotun/taskfirst/task2/NumberOfLines.java
> +    public void enterNumbersAndValuesOfLines() {
same here with method name :) smth like 'enterDataAndPerformCalculations'

2020-10-26 09:56 UTC, merged

2020-10-26 15:53 UTC, YehorKorotun commented on src/com/yehorkorotun/taskfirst/task3/MathOperations.java
> +    public void enterNumbersAndCalculation () {
Modified

2020-10-26 15:53 UTC, YehorKorotun commented on src/com/yehorkorotun/taskfirst/task2/NumberOfLines.java
> +    public void enterNumbersAndValuesOfLines() {
Modified